### ISSUE TITLE
adm-zip dependency

### ISSUE THREAD

**Issue by webmasterkai** [Factisio/factis-store-hexastore#2]
How important is it to have `exportZip` as a dependency of factis-store-hexastore? I ask because I'm looking to run factis-store-hexastore in the browser and am keen on keeping dependencies light. Plus, it looks like adm-zip requires `fs`.

Thanks!

**Comment by crubier** [comment]
Hi, it should be easy to remove this dependency, as it is only used to export the data store to a file.
I will push a new version very soon without this dependency !

**Comment by crubier** [comment]
Done, the dependency was removed in 1.0.3

**Comment by webmasterkai** [comment]
Thanks! :+1:
